apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  # application
  - containerPort: 30000
    hostPort: 30000
  # postgres dataabse
  - containerPort: 31321
    hostPort: 31321
  # Grafana
  - containerPort: 31300
    hostPort: 31300
  # vault
  - containerPort: 31400
    hostPort: 31400
  # debug port
  - containerPort: 30500
    hostPort: 30500
- role: worker
- role: worker
- role: worker

