apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-db-username
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: static-db-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: spring-boot-k8s-template/db
      property: username
  - secretKey: password
    remoteRef:
      key: spring-boot-k8s-template/db
      property: password

