apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
  labels:
    app: ubuntu
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "myapp-k8s-role"
    vault.hashicorp.com/agent-inject-secret-myapp-db: "myapp-db/creds/myapp-db-role"
    vault.hashicorp.com/secret-volume-path-secret-myapp-db: "myapp-db.creds"
    vault.hashicorp.com/auth-path: "auth/kubernetes"
    vault.hashicorp.com/agent-run-as-user: "1881"
    vault.hashicorp.com/agent-pre-populate: "true"
    vault.hashicorp.com/agent-pre-populate-only: "false"
spec:
  serviceAccountName: myapp-sa
  containers:
    - image: ubuntu
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
      name: ubuntu
  restartPolicy: Always